/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/regenerate.ts from https://api.themeparks.wiki/docs/v1.yaml.
 * Do not edit by hand. Run `npm run regenerate` to update.
 */
export interface paths {
    "/v1/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List destinations
         * @description Returns every destination with its parks (id and name). This is the place to start: take an id from here and call GET /v1/entity/{id}/children for what is inside it, /live for what it is doing, or /schedule for its opening hours. Cache it; it rarely changes.
         */
        get: operations["getAllDestinations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an entity
         * @description Returns what this entity is: its name, entityType, timezone, location, parent and park, and its attributes. `id` can be an entity's UUID, its slug or, for a destination, its `externalId`. An unknown or malformed id returns 404. Attributes appear as extra top-level keys named after them, such as `minimumHeight` and `mayGetWet`, so the set of keys varies; read the ones you need. For what the entity is doing now, call GET /v1/entity/{id}/live.
         */
        get: operations["getEntityById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity/{id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the entities inside an entity
         * @description Returns the entities beneath this one as a flat array, each with id, name, entityType, slug, externalId, location and parentId. `id` can be an entity's UUID, its slug or, for a destination, its `externalId`. An unknown or malformed id returns 404. For a DESTINATION or a PARK you get everything inside it, not just one level; for any other entityType you get its direct children. Rebuild the tree from `parentId`. Removed entities are not listed.
         */
        get: operations["getEntityChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History of an entity
         * @description Returns an entity's history as one row per change. Each row is the entity's complete live data at that moment (the same keys as /live) plus `time` and `changed`. Ask for one park-local day (`date=YYYY-MM-DD`), a range of days (`from` and `to`, both inclusive), or RFC 3339 instants with an offset (`to` exclusive). With no parameters you get today. A call covers up to 31 days. The `opening` object is the state at the start of the range: the last reading of every field, however old, with `opening.observedAt` saying when it was seen, so the first row is already complete. `coverage.firstRecordedAt` is the first day we hold anything for this entity.
         *
         *     For a park, the 200 is `HistoryParkRawEnvelope`: an `entities[]` array with the same `coverage`, `opening` object and `history` for each entity that has history, the park included if it has its own. A park call covers 1 park-local day, and a longer range returns 400 RANGE_TOO_LONG. Every other entityType gets the single-entity shape, so the 200 is a union of two schemas selected by `entityType`. A call costs one unit of the hourly history budget, however large the park.
         *
         *     See "Limits" above for the history window and hourly budget.
         */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity/{id}/history/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History held for an entity
         * @description Returns the history we hold for this entity, per field: the first and last park-local day we recorded each field (`status`, `queue.STANDBY`, `showtimes` and so on), keyed by the same live-data paths as /live, /history and /history/daily. Fields the entity never reported are left out of `kinds`. Recording runs 2 to 3 days behind live data, so `last` and `lastRecordedAt` usually trail today by that much, even for a field still being published; use /live to see what is current. `retrievableThrough` is the newest day you can ask /history and /history/daily for, usually today. An entity with nothing recorded returns `kinds: {}` with null days, not 404. For a park, the 200 is `HistoryParkCoverageDocument`, a summary across the park's entities. This call takes no parameters, is not paged and has no history window, but it does spend the hourly history budget.
         *
         *     See "Limits" above for the history window and hourly budget.
         */
        get: operations["getHistoryCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity/{id}/history/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily summaries of an entity's history
         * @description Returns one summary row per park-local day: minutes operating, down and unknown, first opening and last close, wait statistics, show count and change count. Parameters are as for /history; rows cover whole days. A call covers up to 3660 days and is never paged. Days with no data are left out. So are `standby`, `singleRider` and `showCount` when there was nothing of that kind.
         *
         *     A run lasts from a change to OPERATING until the next change to CLOSED or REFURBISHMENT, DOWN periods included. A row is counted like this:
         *
         *     - Outside the park's published hours, an OPERATING status counts as `unknownMinutes`, not `operatingMinutes`, after 4 hours or more unconfirmed. On a day with published hours, only a status change confirms it; a status carried over midnight is unconfirmed. On other days, any change but `showtimes` confirms it, across midnight.
         *     - A wait counts only while the entity is OPERATING and on the day it was posted. The wait showing when a ride opens counts if it last changed within 24 hours.
         *     - `extremeWaits` counts readings of 480 minutes or more, usually feed errors. Nothing is left out: those readings stay in the statistics, and `extremeWaits` flags them.
         *     - `firstOperatingAt` is null when the entity did not change to OPERATING that day; it may still have operated, carried over from the day before.
         *     - `lastClosedAt` is when the last run that started that day closed, which can be after midnight. The next day's row does not repeat it.
         *     - `inParkHours` repeats the numbers for the park's published hours, when it published any.
         *     - A row without `unknownMinutes` was counted under earlier rules.
         *
         *     To rebuild a row from /history, use that day's and the next day's history, the park's schedule for both days, `opening.observedAtByKind` and `opening.observedAt`.
         *
         *     For a park, the 200 is `HistoryParkDailyEnvelope`, with an `entities[]` array in place of `coverage` and `days`. Park calls are paged, 31 park-local days at a time, with `next` for the rest. Every other entityType gets the single-entity shape, so the 200 is a union of two schemas selected by `entityType`. A call costs one unit of the hourly history budget, however large the park.
         *
         *     See "Limits" above for the history window and hourly budget.
         */
        get: operations["getHistoryDaily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity/{id}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live data for an entity
         * @description Returns live data for this entity and everything beneath it: status, wait times, return-time and boarding-group windows, and show times. `id` can be an entity's UUID, its slug or, for a destination, its `externalId`. An unknown or malformed id returns 404. An entity with nothing to report is left out of `liveData`; treat that as no data. Filter by type with `entityType`. The data is current to about a minute. For past data, call GET /v1/entity/{id}/history.
         */
        get: operations["getEntityLiveData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity/{id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Upcoming opening hours
         * @description Returns opening hours from today through the next 30 days, in the entity's own timezone. `id` can be an entity's UUID, its slug or, for a destination, its `externalId`. An unknown or malformed id returns 404. Days the park has not published are left out. For a particular month, past months included, call GET /v1/entity/{id}/schedule/{year}/{month}.
         */
        get: operations["getEntitySchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entity/{id}/schedule/{year}/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Opening hours for a month
         * @description Returns opening hours for one calendar month, in the entity's own timezone. `month` must be two digits (`/2026/09`, not `/2026/9`) and `year` a number from 1970 to 2150; anything else returns 400. `id` can be an entity's UUID, its slug or, for a destination, its `externalId`. An unknown or malformed id returns 404. Past months show what was published at the time. A month before we started recording this entity comes back empty. Days the park has not published are left out.
         */
        get: operations["getEntityScheduleYearMonth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your plan and remaining budgets
         * @description Returns your plan and what is left of it: `tier`, how far back your history calls reach (`historyDays`, or `historyAllArchive: true` when you can read everything we hold), the earliest day you may ask for, and two budgets: `rateLimit`, the request limit every call counts against, and `historyRateLimit`, the hourly history budget. Each budget has `unmetered`; when it is false, it also has `limit`, `windowSeconds`, `remaining` and `reset`, the same figures as the RateLimit headers. Use it on an unmetered plan, which gets no such headers, or to check your history budget without spending it. The call counts as one ordinary request and needs an API key.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 401: this endpoint needs an API key (X-API-Key header) or a session token, and none was sent or the one sent was not accepted. A revoked, mistyped or truncated key answers this too. */
        AuthenticationRequired: {
            /**
             * @description Always false.
             * @enum {boolean}
             */
            success: false;
            error: {
                /** @enum {string} */
                type: "Authentication failed";
                /** @description Says whether no credential was sent or the one sent was not accepted. */
                message: string;
                /**
                 * @description Repeats the HTTP status.
                 * @enum {integer}
                 */
                code?: 401;
            };
        };
        /**
         * @description State of boarding group availability
         * @enum {string}
         */
        BoardingGroupState: "AVAILABLE" | "PAUSED" | "CLOSED";
        Destination: {
            /** @description Unique identifier of the destination */
            id: string;
            /** @description Name of the destination */
            name: string;
            /** @description URL-friendly slug for the destination */
            slug?: string | null;
            /** @description The park operator's own id for this destination */
            externalId?: string | null;
            /** @description Array of parks within this destination */
            parks: components["schemas"]["Park"][];
        };
        DestinationsResponse: {
            /** @description Array of all destinations */
            destinations: components["schemas"]["Destination"][];
        };
        DiningAvailability: {
            /** @description Available party size */
            partySize?: number | null;
            /** @description Current wait time in minutes */
            waitTime?: number | null;
        };
        EntityChild: {
            /** @description Unique entity identifier */
            id: string;
            /** @description Entity name */
            name: string;
            entityType: components["schemas"]["EntityType"];
            /** @description External identifier */
            externalId?: string;
            /** @description Parent entity identifier */
            parentId?: string;
            location?: components["schemas"]["EntityLocation"];
            /** @description URL-friendly slug */
            slug?: string | null;
        };
        EntityChildrenResponse: {
            /** @description Parent entity identifier */
            id?: string;
            /** @description Parent entity name */
            name?: string;
            entityType?: components["schemas"]["EntityType"];
            /** @description Entity timezone */
            timezone?: string;
            children?: components["schemas"]["EntityChild"][];
        };
        /** @description A single entity. It may also carry attribute keys not listed here, named after the attribute, e.g. `minimumHeight` (integer, centimetres) or `mayGetWet` (boolean). Which ones appear varies by entity, so read the ones you need and do not assume any is present. */
        EntityData: {
            /** @description Unique entity identifier */
            id: string;
            /** @description Entity name */
            name: string;
            entityType: components["schemas"]["EntityType"];
            /**
             * @description Kind of attraction. Present on ATTRACTION entities.
             * @enum {string}
             */
            attractionType?: "UNKNOWN" | "RIDE" | "SHOW" | "TRANSPORT" | "PARADE" | "MEET_AND_GREET" | "OTHER";
            /** @description Parent entity identifier */
            parentId?: string | null;
            /** @description Destination identifier */
            destinationId?: string | null;
            /** @description Identifier of the park this entity belongs to. Absent on destinations and on parks themselves. */
            parkId?: string | null;
            /** @description Entity timezone */
            timezone: string;
            location?: components["schemas"]["EntityLocation"];
            /** @description The park operator's own id for this entity. */
            externalId?: string;
            /** @description URL-friendly slug. Served for destinations. */
            slug?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** @description 400: a path parameter is the wrong shape, such as a one-digit `month` or a `year` outside the accepted range. An unknown id returns 404 first. */
        EntityInvalidParameter: {
            /**
             * @description Always false.
             * @enum {boolean}
             */
            success: false;
            error: {
                /** @enum {string} */
                type: "Bad request";
                /** @description Says which parameter was rejected and what it must look like, e.g. "Month must be a two-digit number (01-12)". */
                message: string;
                /**
                 * @description Repeats the HTTP status.
                 * @enum {integer}
                 */
                code?: 400;
            };
        };
        EntityLiveData: {
            /** @description Entity identifier */
            id: string;
            /** @description Entity name */
            name: string;
            entityType: components["schemas"]["EntityType"];
            status?: components["schemas"]["LiveStatusType"];
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            lastUpdated: string;
            queue?: components["schemas"]["LiveQueue"];
            showtimes?: components["schemas"]["LiveShowTime"][];
            operatingHours?: components["schemas"]["LiveShowTime"][];
            diningAvailability?: components["schemas"]["DiningAvailability"][];
        };
        EntityLiveDataResponse: {
            /** @description Entity identifier */
            id?: string;
            /** @description Entity name */
            name?: string;
            entityType?: components["schemas"]["EntityType"];
            /** @description Entity timezone */
            timezone?: string;
            liveData?: components["schemas"]["EntityLiveData"][];
        };
        EntityLocation: {
            /** @description Latitude coordinate of the entity location */
            latitude?: number | null;
            /** @description Longitude coordinate of the entity location */
            longitude?: number | null;
        };
        /** @description 404: nothing matches `id` (a UUID, a slug, or a destination's externalId; a malformed id is 404 too). The answer is the same whether it never existed or was removed. */
        EntityNotFound: {
            /**
             * @description Always false.
             * @enum {boolean}
             */
            success: false;
            error: {
                /** @enum {string} */
                type: "Not found";
                /** @description Names the id that did not resolve, e.g. "Entity 00000000-0000-0000-0000-000000000000 not found". */
                message: string;
                /**
                 * @description Repeats the HTTP status.
                 * @enum {integer}
                 */
                code?: 404;
            };
        };
        EntityScheduleResponse: {
            /** @description Entity identifier */
            id?: string;
            /** @description Entity name */
            name?: string;
            /** @description Type of entity */
            entityType?: components["schemas"]["EntityType"];
            /** @description Entity timezone */
            timezone?: string;
            schedule?: components["schemas"]["ScheduleEntry"][];
            /** @description Only included for destinations, lists all parks within the destination */
            parks?: components["schemas"]["ParkSchedule"][];
        };
        /**
         * @description Type of entity in the theme park system
         * @enum {string}
         */
        EntityType: "DESTINATION" | "PARK" | "ATTRACTION" | "RESTAURANT" | "HOTEL" | "SHOW";
        HistoryCoverage: {
            /**
             * Format: date
             * @description First park-local day we hold anything for this entity, or null. Per-field detail: GET /v1/entity/{id}/history/coverage.
             */
            firstRecordedAt: string | null;
        };
        /** @description What history we hold for one entity, per field. An entity with nothing recorded is a 200 with `kinds: {}` and null days, not 404. For a PARK the same call returns HistoryParkCoverageDocument. */
        HistoryCoverageDocument: {
            id: string;
            name: string;
            entityType: string;
            parentId: string | null;
            destinationId: string | null;
            /** @description IANA timezone the park-local days are resolved in. */
            timezone: string;
            /**
             * Format: date
             * @description First park-local day we hold anything for this entity, or null.
             */
            firstRecordedAt: string | null;
            /**
             * Format: date
             * @description The newest `last` across `kinds`, or null.
             */
            lastRecordedAt: string | null;
            /**
             * Format: date
             * @description The newest day you can ask /history and /history/daily for: usually today for an entity still reporting, or its last recorded day for one that stopped long ago. Null when we hold nothing. Your history window limits how far back you can ask.
             */
            retrievableThrough: string | null;
            /** @description Keyed by live-data path (status, queue.STANDBY, showtimes and so on), as /live and /history name them. Fields the entity never reported are left out. */
            kinds: {
                [key: string]: components["schemas"]["HistoryCoverageKindSpan"];
            };
        };
        /** @description One live-data field's recorded span for an entity, both ends inclusive. */
        HistoryCoverageKindSpan: {
            /**
             * Format: date
             * @description First park-local day this field was reported.
             */
            first: string;
            /**
             * Format: date
             * @description The newest day we hold this field for. The coverage call says how far it trails today.
             */
            last: string;
        };
        /** @description One entity's daily summary. For a PARK the same call returns HistoryParkDailyEnvelope. range is always whole park-local days (YYYY-MM-DD), and today's row is the day so far. */
        HistoryDailyEnvelope: {
            id: string;
            name: string;
            entityType: string;
            parentId: string | null;
            destinationId: string | null;
            /** @description IANA timezone the park-local days are resolved in. */
            timezone: string;
            range: components["schemas"]["HistoryRange"];
            coverage: components["schemas"]["HistoryCoverage"];
            /** @description One row per day, ascending. Days with no data are left out. */
            days: components["schemas"]["HistoryDailyRow"][];
            /** @description Always null for a single entity. */
            next: string | null;
        };
        /** @description How many wait readings of 480 minutes or more the day's statistics include. Such readings are usually feed errors (values like 999); they are counted here as a flag and stay in every statistic. Counted per reading while OPERATING. Present only when there were some, and then with both counts. */
        HistoryDailyExtremeWaits: {
            /** @description Standby readings of 480 minutes or more included in the day's standby statistics. */
            standby: number;
            /** @description Single-rider readings of 480 minutes or more included in the day's single-rider statistics. */
            singleRider: number;
        };
        /** @description The day's numbers limited to the park's published hours. Present only when the park published hours that day. */
        HistoryDailyInParkHours: {
            /** @description Minutes of the day inside the park's published hours: its schedule entries of type OPERATING, EXTRA_HOURS and TICKETED_EVENT. Hours from the previous day's schedule that run past midnight are not included. Today counts elapsed minutes only. */
            scheduledMinutes: number;
            /** @description Of scheduledMinutes, the minutes the entity was OPERATING. */
            operatingMinutes: number;
            /** @description Of scheduledMinutes, the minutes the entity was DOWN. */
            downMinutes: number;
            /** @description Of scheduledMinutes, the minutes with no known status. */
            unknownMinutes: number;
            standby?: components["schemas"]["HistoryDailyStats"];
            singleRider?: components["schemas"]["HistoryDailyStats"];
            extremeWaits?: components["schemas"]["HistoryDailyExtremeWaits"];
        };
        /** @description One day of an entity's history. standby, singleRider, extremeWaits, showCount and inParkHours are absent when there is nothing to report; a standby block needs a valid wait showing for at least one whole minute. A row without unknownMinutes was counted under earlier rules, and also lacks extremeWaits and inParkHours. */
        HistoryDailyRow: {
            /**
             * Format: date
             * @description The park-local calendar day this row summarises, YYYY-MM-DD, in the entity's timezone.
             */
            date: string;
            /**
             * Format: date-time
             * @description When the entity changed to OPERATING that day (UTC, whole seconds). null when it did not change to OPERATING that day; it may still have operated, carried over from the day before.
             */
            firstOperatingAt: string | null;
            /**
             * Format: date-time
             * @description When the last run that started this day closed (UTC, whole seconds). A run lasts from a change to OPERATING until the next change to CLOSED or REFURBISHMENT, DOWN periods included. A run still going at midnight closes the next day and is reported on this row. null if it did not close by the end of the next day, or if the close came after 4 hours or more outside published hours with nothing to confirm the run (see unknownMinutes: a change of status on a day with published hours, a change to any field other than showtimes on a day without).
             */
            lastClosedAt: string | null;
            /** @description Minutes OPERATING with a known status. Today counts elapsed minutes only. CLOSED and REFURBISHMENT minutes are not counted, so operatingMinutes, downMinutes and unknownMinutes need not add up to the day. */
            operatingMinutes: number;
            /** @description Minutes DOWN. Today counts elapsed minutes only. */
            downMinutes: number;
            /** @description Minutes with no known status: none was reported, or the entity was OPERATING outside the park's published hours with nothing to confirm it for 4 hours or more. On a day the park published hours, only a change of status confirms it, and a status carried over midnight is unknown outside those hours until it changes. On a day with no published hours, or for an entity outside any park, a change to any field other than showtimes (status, a wait or anything else) confirms it, and for a status carried over midnight the hours count from the last change before midnight. Absent on rows counted under earlier rules. */
            unknownMinutes?: number;
            standby?: components["schemas"]["HistoryDailyStats"];
            singleRider?: components["schemas"]["HistoryDailyStats"];
            extremeWaits?: components["schemas"]["HistoryDailyExtremeWaits"];
            /** @description Distinct performance start times whose park-local day is this day. Present only for entities that published showtimes on the day. */
            showCount?: number;
            inParkHours?: components["schemas"]["HistoryDailyInParkHours"];
            /** @description How many times any field changed this day. */
            changes: number;
        };
        /** @description Wait statistics for the day. p50, mean and p90 are weighted by how many minutes each wait was showing; min and max are the extremes of every value posted. Only minutes where the entity was OPERATING (not unknown) and the wait was valid count. A wait is valid during the run and on the day it was posted; the wait showing when a ride opens counts from the opening if it last changed within 24 hours; a wait carried over midnight does not count until it changes. Nothing the park reported is excluded: a reading of 480 minutes or more stays in these statistics and is counted in the row's `extremeWaits`. Absent when no minute counted. */
        HistoryDailyStats: {
            /** @description Lowest wait posted during the counted minutes, including one that showed for under a minute. */
            min: number;
            /** @description Median wait, weighted by minutes; always a value that was actually posted. */
            p50: number;
            /** @description Minute-weighted average wait, rounded to the nearest whole minute. */
            mean: number;
            /** @description 90th-percentile wait, weighted by minutes. */
            p90: number;
            /** @description Highest wait posted during the counted minutes, including a brief spike. It can be a feed error: the row's extremeWaits counts readings of 480 minutes or more. */
            max: number;
        };
        /** @description One entity's history. For a PARK the same call returns HistoryParkRawEnvelope instead. */
        HistoryEnvelope: {
            id: string;
            name: string;
            entityType: string;
            parentId: string | null;
            destinationId: string | null;
            /** @description IANA timezone the park-local days are resolved in. */
            timezone: string;
            range: components["schemas"]["HistoryRange"];
            coverage: components["schemas"]["HistoryCoverage"];
            opening: components["schemas"]["HistoryOpening"];
            /** @description Ascending by time. */
            history: components["schemas"]["HistoryRow"][];
            /** @description Always null for a single entity. */
            next: string | null;
        };
        /** @description 502: history is temporarily unavailable. Retry shortly. */
        HistoryErrorBackendUnavailable: {
            error: {
                /** @enum {string} */
                type: "HISTORY_BACKEND_UNAVAILABLE";
                message: string;
            };
        };
        /** @description 400: a date parameter is not a calendar day or an RFC 3339 instant with an explicit offset, or date was combined with from/to, or from and to mix the two forms, or to was given without from. */
        HistoryErrorInvalidDate: {
            error: {
                /** @enum {string} */
                type: "INVALID_DATE";
                /** @description e.g. "from must be a calendar day (YYYY-MM-DD) or an RFC 3339 instant with an offset (e.g. 2026-09-13T14:00:00Z)." */
                message: string;
            };
        };
        /** @description 400: both ends parsed, but the range runs backwards (days: to before from; instants: to not after from). */
        HistoryErrorInvalidRange: {
            error: {
                /** @enum {string} */
                type: "INVALID_RANGE";
                /** @description e.g. "to must not be before from." */
                message: string;
            };
        };
        /** @description 404: no entity with that id. */
        HistoryErrorNotFound: {
            error: {
                /** @enum {string} */
                type: "NOT_FOUND";
                message: string;
            };
        };
        /** @description 400: the range is too long. The limit is not the same on every path: 31 days on /history (1 for a park), and 3660 on /history/daily (a park pages at 31 instead). Split the range into shorter calls. */
        HistoryErrorRangeTooLong: {
            error: {
                /** @enum {string} */
                type: "RANGE_TOO_LONG";
                /** @description Names the limit that applied and your span, e.g. "A history call covers at most 31 park-local days (2026-01-01 to 2026-03-01 is 60)." */
                message: string;
            };
        };
        /** @description 429: your hourly history budget is spent. It is separate from the per-minute limit; the limits per plan are on the pricing page. */
        HistoryErrorRateLimited: {
            error: {
                /** @enum {string} */
                type: "HISTORY_RATE_LIMITED";
                /** @description e.g. "This key can make 600 history requests an hour." */
                message: string;
                /** @description Seconds until the hourly history budget admits another request. Also sent as the Retry-After header. */
                retryAfter: number;
            };
        };
        HistoryErrorWindowExceeded: {
            error: {
                /** @enum {string} */
                type: "HISTORY_WINDOW_EXCEEDED";
                /** @description e.g. "This key can see history back to 2026-09-08 (7 days)." */
                message: string;
                /**
                 * Format: date
                 * @description First park-local day this credential may query.
                 */
                earliestAllowedDate: string;
            };
        };
        /** @description The `opening` object: the complete state at the start of the range, in the same shape as a row. A field is present only if the entity has it. An unknown value is its empty form (standby `{"waitTime": null}`, showtimes `[]`); an unknown status is null. */
        HistoryOpening: {
            /**
             * Format: date-time
             * @description Start of the range (UTC, whole seconds). The state below is effective from this instant.
             */
            time: string;
            /**
             * Format: date-time
             * @description When this state was last seen (UTC, whole seconds): the newest entry in `observedAtByKind`. Earlier than `time` means it was carried in from before the range, possibly from long ago; a ride whose feed stopped keeps its last values. Absent means we hold nothing for this entity from before the range, unless `degraded` is set.
             */
            observedAt?: string;
            /** @description When each field of the opening was last seen (UTC, whole seconds), keyed by its path: `status`, `queue.STANDBY`, `showtimes` and so on. A wait that did not change for weeks is dated weeks back, so check a queue's own entry before treating it as current. Usually, but not always, the moment the value last changed. */
            observedAtByKind?: {
                [key: string]: string;
            };
            /**
             * @description Present, and true, when we could not look far enough back for this response, so the opening may be missing a field we hold. Ask again in a minute for the full opening.
             * @enum {boolean}
             */
            degraded?: true;
            /**
             * @description Why the lookup was cut short: `timeout`, `error`, or `capacity` when it needed more reading than one request is allowed.
             * @enum {string}
             */
            degradedReason?: "timeout" | "error" | "capacity";
            /** @description Live status at the start of the range; null when unknown. */
            status?: string | null;
            queue?: components["schemas"]["LiveQueue"];
            showtimes?: components["schemas"]["LiveShowTime"][] | null;
        };
        /** @description How far back each entity's record of this field goes, as counts per band of calendar years, measured from `summary.measuredOn`. */
        HistoryParkCoverageDepth: {
            /** @description Entities whose record of this field goes back four calendar years or more. */
            fourYearsPlus: number;
            /** @description Entities with at least two and under four calendar years. */
            twoToFourYears: number;
            /** @description Entities with at least one and under two calendar years. */
            oneToTwoYears: number;
            /** @description Entities with under a calendar year, usually something that opened recently. */
            underOneYear: number;
        };
        /** @description What history we hold across a whole PARK, returned by /history/coverage when the entity is a PARK. Its names map to the single-entity document: `fields` is `kinds`, and each `from` and `newest` is a `first` and `last`. It reports depth and breadth; it does not find missing days. */
        HistoryParkCoverageDocument: {
            id: string;
            name: string;
            entityType: string;
            parentId: string | null;
            destinationId: string | null;
            /** @description IANA timezone of the park. */
            timezone: string;
            summary: components["schemas"]["HistoryParkCoverageSummary"];
            /** @description Keyed by live-data field path, in live-data order. */
            fields: {
                [key: string]: components["schemas"]["HistoryParkCoverageField"];
            };
            /** @description Every entity of the park history is held for. */
            entities: components["schemas"]["HistoryParkCoverageEntity"][];
        };
        /** @description One entity we hold history for. Entities with none (often parades, shows and lands) are absent. */
        HistoryParkCoverageEntity: {
            id: string;
            name: string;
            entityType: string;
            /**
             * Format: date
             * @description The earliest park-local day any field of this entity was recorded.
             */
            from: string;
            /**
             * Format: date
             * @description The newest park-local day any field of this entity was recorded.
             */
            newest: string;
            /** @description Field paths held, named as in the single-entity coverage document. */
            fields: string[];
            /** @description false when the park no longer lists this entity. Its history is still available. */
            stillListed: boolean;
        };
        /** @description One field across the park. `entities` counts the entities we hold it for; entities that never reported it are not counted. */
        HistoryParkCoverageField: {
            /** @description How many of the park's entities this field is held for. */
            entities: number;
            /**
             * Format: date
             * @description The earliest park-local day any entity in the park reported this field.
             */
            from: string;
            /**
             * Format: date
             * @description Newest day any entity reported it. A past day can mean the park stopped publishing the field.
             */
            newest: string;
            depth: components["schemas"]["HistoryParkCoverageDepth"];
        };
        /** @description Summary figures for the park, all describing what we hold. */
        HistoryParkCoverageSummary: {
            /** @description Entities we hold any history for, including ones the park no longer lists (`stillListed: false`). */
            entitiesWithData: number;
            /**
             * Format: date
             * @description Earliest day anything in this park was recorded, or null.
             */
            archiveFrom: string;
            /**
             * Format: date
             * @description The newest park-local day anything in this park was recorded, or null.
             */
            recordedTo: string;
            /**
             * Format: date
             * @description The newest day you can ask for, usually today. Null when nothing is recorded.
             */
            retrievableThrough: string;
            /**
             * Format: date
             * @description The day these figures were computed; they grow over time.
             */
            measuredOn: string;
        };
        /** @description The daily summary of a whole PARK, returned by /history/daily when the entity's entityType is PARK. A call serves up to 31 park-local days; `range.to` is this page's last day. */
        HistoryParkDailyEnvelope: {
            id: string;
            name: string;
            entityType: string;
            parentId: string | null;
            destinationId: string | null;
            /** @description IANA timezone of the park; every entity is summarised in it. */
            timezone: string;
            range: components["schemas"]["HistoryRange"];
            /** @description One entry per entity with history, by name. Entities with no history are absent. */
            entities: components["schemas"]["HistoryParkEntityDaily"][];
            /** @description Absolute URL of the next page (your parameters kept, `from` moved on), or null on the last page. Up to 31 park-local days a page. */
            next: string | null;
        };
        /** @description One entity of the park, with its first recorded day and its rows. The park appears too if it has history of its own. */
        HistoryParkEntityDaily: {
            id: string;
            name: string;
            entityType: string;
            coverage: components["schemas"]["HistoryCoverage"];
            /** @description The entity's rows for this page, as /history/daily returns them for the entity alone. Empty when it has no data in these days. */
            days: components["schemas"]["HistoryDailyRow"][];
        };
        /** @description One entity of the park, with the same coverage, opening and history as a single-entity call. The park appears too if it has history of its own. */
        HistoryParkEntityRaw: {
            id: string;
            name: string;
            entityType: string;
            coverage: components["schemas"]["HistoryCoverage"];
            opening: components["schemas"]["HistoryOpening"];
            /** @description Ascending by time. Empty when nothing changed in the range. */
            history: components["schemas"]["HistoryRow"][];
        };
        /** @description History of a whole PARK for 1 park-local day, returned by /history when the entity's entityType is PARK. A longer range is 400 RANGE_TOO_LONG. */
        HistoryParkRawEnvelope: {
            id: string;
            name: string;
            entityType: string;
            parentId: string | null;
            destinationId: string | null;
            /** @description IANA timezone of the park; every entity is resolved in it. */
            timezone: string;
            range: components["schemas"]["HistoryRange"];
            /** @description One entry per entity with history, by name. Entities with no history are absent. */
            entities: components["schemas"]["HistoryParkEntityRaw"][];
            /** @description Always null: one day per call. */
            next: string | null;
        };
        HistoryRange: {
            /** @description The start you asked for. A day comes back as you sent it; an instant comes back normalised to UTC whole seconds. On /history/daily it is always a day. */
            from: string;
            /** @description The end, in the same form as from. Defaults to today (days) or now (instants). */
            to: string;
        };
        /** @description One row per moment any field changed. Every field is carried forward, so each row is the complete live data at that moment (same keys as GET /v1/entity/{id}/live). */
        HistoryRow: {
            /**
             * Format: date-time
             * @description UTC instant (whole seconds) from which this state is effective, until the next row's time.
             */
            time: string;
            /** @description Leaf paths that differ from the previous row (or from opening for the first row), e.g. queue.STANDBY.waitTime, status, showtimes. */
            changed: string[];
            status?: string | null;
            queue?: components["schemas"]["LiveQueue"];
            showtimes?: components["schemas"]["LiveShowTime"][] | null;
        };
        /** @description The queues an entity has, each present only when the entity publishes it. STANDBY: the ordinary line. SINGLE_RIDER: a separate line for guests riding alone. RETURN_TIME: a free reservation for a later time window. PAID_RETURN_TIME: the same, paid for. BOARDING_GROUP: a virtual queue that calls groups by number. PAID_STANDBY: a paid line with its own wait. */
        LiveQueue: {
            STANDBY?: {
                /** @description Current standby wait time in minutes */
                waitTime?: number | null;
            };
            SINGLE_RIDER?: {
                /** @description Current single rider wait time in minutes */
                waitTime: number | null;
            };
            RETURN_TIME?: {
                state: components["schemas"]["ReturnTimeState"] | null;
                /**
                 * Format: date-time
                 * @description Start time of return window
                 */
                returnStart: string | null;
                /**
                 * Format: date-time
                 * @description End time of return window
                 */
                returnEnd: string | null;
            };
            PAID_RETURN_TIME?: {
                state: components["schemas"]["ReturnTimeState"] | null;
                /** Format: date-time */
                returnStart: string | null;
                /** Format: date-time */
                returnEnd: string | null;
                price: components["schemas"]["PriceData"] | null;
            };
            BOARDING_GROUP?: {
                allocationStatus: components["schemas"]["BoardingGroupState"] | null;
                /** @description Current boarding group start number */
                currentGroupStart: number | null;
                /** @description Current boarding group end number */
                currentGroupEnd: number | null;
                /**
                 * Format: date-time
                 * @description Next boarding group allocation time
                 */
                nextAllocationTime: string | null;
                /** @description Estimated wait time in minutes */
                estimatedWait: number | null;
            };
            PAID_STANDBY?: {
                /** @description Current paid standby wait time in minutes */
                waitTime: number | null;
            };
        };
        LiveShowTime: {
            /** @description Type of show time entry */
            type: string;
            /**
             * Format: date-time
             * @description Start time of the show
             */
            startTime?: string | null;
            /**
             * Format: date-time
             * @description End time of the show
             */
            endTime?: string | null;
        };
        /**
         * @description An entity's status. OPERATING: open and running. DOWN: stopped for now, for example by a breakdown, when it would otherwise be running. CLOSED: not open. REFURBISHMENT: closed for a longer period of maintenance or rebuilding.
         * @enum {string}
         */
        LiveStatusType: "OPERATING" | "DOWN" | "CLOSED" | "REFURBISHMENT";
        Park: {
            /** @description Unique identifier of the park */
            id: string;
            /** @description Name of the park */
            name: string;
        };
        ParkSchedule: {
            /** @description Entity identifier */
            id?: string;
            /** @description Entity name */
            name?: string;
            /** @description Type of entity */
            entityType?: components["schemas"]["EntityType"];
            /** @description Entity timezone */
            timezone?: string;
            schedule?: components["schemas"]["ScheduleEntry"][];
        };
        /** @description 503: your plan could not be read just now. Try again after the Retry-After header's number of seconds. */
        PlanUnavailable: {
            /** @enum {boolean} */
            success: false;
            error: {
                /** @enum {string} */
                type: "Server error";
                message: string;
                /** @enum {integer} */
                code?: 503;
            };
        };
        PriceData: {
            /** @description Numerical price amount, in the currency's lowest denomination (e.g. cents). null when the item costs money but the provider does not publish an amount; 0 means genuinely free */
            amount: number | null;
            /** @description Currency code */
            currency: string;
            /** @description Formatted price string */
            formatted?: string;
        };
        /** @description 429 from the request limit every call counts against. See "Limits" at the top of this document. */
        RateLimited: {
            /** @enum {string} */
            error: "Too Many Requests";
            /** @description What happened, e.g. "Too Many Requests". */
            message: string;
            /** @description Seconds to wait before retrying. Also sent as the Retry-After header. */
            retryAfter: number;
            /** @description Present when you were looking entities up one guessed slug at a time: the call to make instead, e.g. "GET /v1/destinations". */
            useInstead?: string;
        };
        /**
         * @description State of return time availability
         * @enum {string}
         */
        ReturnTimeState: "AVAILABLE" | "TEMP_FULL" | "FINISHED";
        ScheduleEntry: {
            /**
             * Format: YYYY-MM-DD
             * @description Schedule date
             */
            date: string;
            /**
             * Format: date-time
             * @description Opening time
             */
            openingTime: string;
            /**
             * Format: date-time
             * @description Closing time
             */
            closingTime: string;
            /**
             * @description Type of schedule entry
             * @enum {string}
             */
            type: "OPERATING" | "TICKETED_EVENT" | "PRIVATE_EVENT" | "EXTRA_HOURS" | "INFO";
            /** @description Optional description of the schedule entry */
            description?: string;
            /** @description Available purchases for this schedule entry */
            purchases?: components["schemas"]["SchedulePriceObject"][];
        };
        SchedulePriceObject: {
            /** @description Type of price object */
            type?: components["schemas"]["SchedulePriceType"];
            /** @description Unique identifier */
            id?: string;
            /** @description Name of the price object */
            name?: string;
            /** @description Price of this purchase option */
            price?: components["schemas"]["PriceData"];
            /** @description Whether this price option is available */
            available?: boolean;
        };
        /**
         * @description Type of schedule price
         * @enum {string}
         */
        SchedulePriceType: "ADMISSION" | "PACKAGE" | "ATTRACTION";
        /** @description Your plan and what is left of it. `rateLimit` is the request limit every call counts against, this one included. `historyRateLimit` is the hourly budget the history calls count against; reading it here does not spend it. Figures are per account, so every key on one account reports the same. */
        V1Me: {
            /** @description Your plan, e.g. "free", "pro", "business", "enterprise". */
            tier: string;
            /** @description How many days back your history calls may reach, today included. null when `historyAllArchive` is true. */
            historyDays: number | null;
            /** @description true when this key can read everything we hold for an entity, back to the first day we recorded it. `historyDays` and `historyEarliestDate` are then null. */
            historyAllArchive: boolean;
            /**
             * Format: date
             * @description The earliest day (YYYY-MM-DD) a history call may ask for, computed in UTC. Each park counts days in its own time zone, so near midnight this can be off by one. Earlier days answer 403 HISTORY_WINDOW_EXCEEDED. null when `historyAllArchive` is true.
             */
            historyEarliestDate: string | null;
            rateLimit: components["schemas"]["V1MeBudget"];
            historyRateLimit: components["schemas"]["V1MeBudget"];
        };
        /** @description One budget: the same figures the RateLimit-* and RateLimit-History-* headers carry. */
        V1MeBudget: {
            /** @description true when this budget is not metered on your plan. The other fields are then absent, and no RateLimit headers are sent for it. */
            unmetered: boolean;
            /** @description Requests allowed per window. */
            limit?: number;
            /** @description Window length in seconds. */
            windowSeconds?: number;
            /** @description Requests left in the current window; null if it could not be read just now. */
            remaining?: number | null;
            /** @description Seconds until the window resets; null if nothing has been counted in this window yet, or if it could not be read. */
            reset?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllDestinations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationsResponse"];
                };
            };
            /** @description Too many requests. Wait `retryAfter` seconds (also the Retry-After header). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimited"];
                };
            };
        };
    };
    getEntityById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity: its UUID, its slug, or for a destination its `externalId`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityData"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityNotFound"];
                };
            };
            /** @description Too many requests. Wait `retryAfter` seconds (also the Retry-After header). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimited"];
                };
            };
        };
    };
    getEntityChildren: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity: its UUID, its slug, or for a destination its `externalId`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityChildrenResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityNotFound"];
                };
            };
            /** @description Too many requests. Wait `retryAfter` seconds (also the Retry-After header). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimited"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query?: {
                /** @description One park-local day, YYYY-MM-DD. Cannot be combined with from/to. */
                date?: string;
                /** @description Start: a park-local day (YYYY-MM-DD, inclusive) or an RFC 3339 instant with an offset (inclusive). from and to must be the same form. */
                from?: string;
                /** @description End: a day (inclusive) or an instant (exclusive). Defaults to today, or now. Up to 31 park-local days per call for a single entity. For a park, 1 park-local day, and a longer range returns 400 RANGE_TOO_LONG. */
                to?: string;
            };
            header?: never;
            path: {
                /** @description The entity: its UUID, its slug, or for a destination its `externalId`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEnvelope"] | components["schemas"]["HistoryParkRawEnvelope"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryErrorInvalidDate"] | components["schemas"]["HistoryErrorInvalidRange"] | components["schemas"]["HistoryErrorRangeTooLong"];
                };
            };
            /** @description Access forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryErrorWindowExceeded"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryErrorNotFound"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryErrorRateLimited"] | components["schemas"]["RateLimited"];
                };
            };
            /** @description Temporarily unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryErrorBackendUnavailable"];
                };
            };
        };
    };
    getHistoryCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity: its UUID, its slug, or for a destination its `externalId`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryCoverageDocument"] | components["schemas"]["HistoryParkCoverageDocument"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryErrorNotFound"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryErrorRateLimited"] | components["schemas"]["RateLimited"];
                };
            };
        };
    };
    getHistoryDaily: {
        parameters: {
            query?: {
                /** @description One park-local day, YYYY-MM-DD. Cannot be combined with from/to. */
                date?: string;
                /** @description Start: a park-local day (YYYY-MM-DD) or an RFC 3339 instant with an offset; rows are always whole days. from and to must be the same form. */
                from?: string;
                /** @description End: a day (inclusive) or an instant (exclusive). Defaults to today. Up to 3660 park-local days per call. */
                to?: string;
            };
            header?: never;
            path: {
                /** @description The entity: its UUID, its slug, or for a destination its `externalId`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDailyEnvelope"] | components["schemas"]["HistoryParkDailyEnvelope"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryErrorInvalidDate"] | components["schemas"]["HistoryErrorInvalidRange"] | components["schemas"]["HistoryErrorRangeTooLong"];
                };
            };
            /** @description Access forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryErrorWindowExceeded"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryErrorNotFound"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryErrorRateLimited"] | components["schemas"]["RateLimited"];
                };
            };
        };
    };
    getEntityLiveData: {
        parameters: {
            query?: {
                /** @description Only return entities of these types, comma-separated, e.g. ATTRACTION,SHOW. */
                entityType?: string;
            };
            header?: never;
            path: {
                /** @description The entity: its UUID, its slug, or for a destination its `externalId`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityLiveDataResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityNotFound"];
                };
            };
            /** @description Too many requests. Wait `retryAfter` seconds (also the Retry-After header). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimited"];
                };
            };
        };
    };
    getEntitySchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity: its UUID, its slug, or for a destination its `externalId`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityScheduleResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityNotFound"];
                };
            };
            /** @description Too many requests. Wait `retryAfter` seconds (also the Retry-After header). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimited"];
                };
            };
        };
    };
    getEntityScheduleYearMonth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entity: its UUID, its slug, or for a destination its `externalId`. */
                id: string;
                /** @description A year from 1970 to 2150, e.g. 2026. */
                year: string;
                /** @description Month as two digits, 01 to 12. */
                month: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityScheduleResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityInvalidParameter"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityNotFound"];
                };
            };
            /** @description Too many requests. Wait `retryAfter` seconds (also the Retry-After header). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimited"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V1Me"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationRequired"];
                };
            };
            /** @description Too many requests. Wait `retryAfter` seconds (also the Retry-After header). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimited"];
                };
            };
            /** @description Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanUnavailable"];
                };
            };
        };
    };
}
