/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DestinationParkEntry from './DestinationParkEntry';

/**
 * The DestinationEntry model module.
 * @module model/DestinationEntry
 * @version 6.0.1
 */
class DestinationEntry {
    /**
     * Constructs a new <code>DestinationEntry</code>.
     * @alias module:model/DestinationEntry
     */
    constructor() { 
        
        DestinationEntry.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DestinationEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DestinationEntry} obj Optional instance to populate.
     * @return {module:model/DestinationEntry} The populated <code>DestinationEntry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DestinationEntry();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('parks')) {
                obj['parks'] = ApiClient.convertToType(data['parks'], [DestinationParkEntry]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
DestinationEntry.prototype['id'] = undefined;

/**
 * @member {String} name
 */
DestinationEntry.prototype['name'] = undefined;

/**
 * @member {String} slug
 */
DestinationEntry.prototype['slug'] = undefined;

/**
 * @member {Array.<module:model/DestinationParkEntry>} parks
 */
DestinationEntry.prototype['parks'] = undefined;






export default DestinationEntry;

