/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityType from './EntityType';
import ScheduleEntry from './ScheduleEntry';

/**
 * The EntityScheduleResponse model module.
 * @module model/EntityScheduleResponse
 * @version 6.0.0
 */
class EntityScheduleResponse {
    /**
     * Constructs a new <code>EntityScheduleResponse</code>.
     * @alias module:model/EntityScheduleResponse
     */
    constructor() { 
        
        EntityScheduleResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntityScheduleResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityScheduleResponse} obj Optional instance to populate.
     * @return {module:model/EntityScheduleResponse} The populated <code>EntityScheduleResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityScheduleResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('entityType')) {
                obj['entityType'] = EntityType.constructFromObject(data['entityType']);
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = ApiClient.convertToType(data['schedule'], [ScheduleEntry]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
EntityScheduleResponse.prototype['id'] = undefined;

/**
 * @member {String} name
 */
EntityScheduleResponse.prototype['name'] = undefined;

/**
 * @member {module:model/EntityType} entityType
 */
EntityScheduleResponse.prototype['entityType'] = undefined;

/**
 * @member {String} timezone
 */
EntityScheduleResponse.prototype['timezone'] = undefined;

/**
 * @member {Array.<module:model/ScheduleEntry>} schedule
 */
EntityScheduleResponse.prototype['schedule'] = undefined;






export default EntityScheduleResponse;

