/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityType from './EntityType';

/**
 * The EntityChild model module.
 * @module model/EntityChild
 * @version 6.0.0
 */
class EntityChild {
    /**
     * Constructs a new <code>EntityChild</code>.
     * @alias module:model/EntityChild
     * @param id {String} 
     * @param name {String} 
     * @param entityType {module:model/EntityType} 
     */
    constructor(id, name, entityType) { 
        
        EntityChild.initialize(this, id, name, entityType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, entityType) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['entityType'] = entityType;
    }

    /**
     * Constructs a <code>EntityChild</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityChild} obj Optional instance to populate.
     * @return {module:model/EntityChild} The populated <code>EntityChild</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityChild();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('entityType')) {
                obj['entityType'] = EntityType.constructFromObject(data['entityType']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
EntityChild.prototype['id'] = undefined;

/**
 * @member {String} name
 */
EntityChild.prototype['name'] = undefined;

/**
 * @member {module:model/EntityType} entityType
 */
EntityChild.prototype['entityType'] = undefined;






export default EntityChild;

