/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class EntityType.
* @enum {}
* @readonly
*/
export default class EntityType {
    
        /**
         * value: "DESTINATION"
         * @const
         */
        "DESTINATION" = "DESTINATION";

    
        /**
         * value: "PARK"
         * @const
         */
        "PARK" = "PARK";

    
        /**
         * value: "ATTRACTION"
         * @const
         */
        "ATTRACTION" = "ATTRACTION";

    
        /**
         * value: "RESTAURANT"
         * @const
         */
        "RESTAURANT" = "RESTAURANT";

    
        /**
         * value: "HOTEL"
         * @const
         */
        "HOTEL" = "HOTEL";

    
        /**
         * value: "SHOW"
         * @const
         */
        "SHOW" = "SHOW";

    

    /**
    * Returns a <code>EntityType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/EntityType} The enum <code>EntityType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

