/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityLiveData from './EntityLiveData';
import EntityType from './EntityType';

/**
 * The EntityLiveDataResponse model module.
 * @module model/EntityLiveDataResponse
 * @version 6.0.1
 */
class EntityLiveDataResponse {
    /**
     * Constructs a new <code>EntityLiveDataResponse</code>.
     * @alias module:model/EntityLiveDataResponse
     */
    constructor() { 
        
        EntityLiveDataResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntityLiveDataResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityLiveDataResponse} obj Optional instance to populate.
     * @return {module:model/EntityLiveDataResponse} The populated <code>EntityLiveDataResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityLiveDataResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('entityType')) {
                obj['entityType'] = EntityType.constructFromObject(data['entityType']);
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('liveData')) {
                obj['liveData'] = ApiClient.convertToType(data['liveData'], [EntityLiveData]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
EntityLiveDataResponse.prototype['id'] = undefined;

/**
 * @member {String} name
 */
EntityLiveDataResponse.prototype['name'] = undefined;

/**
 * @member {module:model/EntityType} entityType
 */
EntityLiveDataResponse.prototype['entityType'] = undefined;

/**
 * @member {String} timezone
 */
EntityLiveDataResponse.prototype['timezone'] = undefined;

/**
 * @member {Array.<module:model/EntityLiveData>} liveData
 */
EntityLiveDataResponse.prototype['liveData'] = undefined;






export default EntityLiveDataResponse;

