/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityChild from './EntityChild';
import EntityType from './EntityType';

/**
 * The EntityChildrenResponse model module.
 * @module model/EntityChildrenResponse
 * @version 6.0.0
 */
class EntityChildrenResponse {
    /**
     * Constructs a new <code>EntityChildrenResponse</code>.
     * @alias module:model/EntityChildrenResponse
     */
    constructor() { 
        
        EntityChildrenResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntityChildrenResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityChildrenResponse} obj Optional instance to populate.
     * @return {module:model/EntityChildrenResponse} The populated <code>EntityChildrenResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityChildrenResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('entityType')) {
                obj['entityType'] = EntityType.constructFromObject(data['entityType']);
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('children')) {
                obj['children'] = ApiClient.convertToType(data['children'], [EntityChild]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
EntityChildrenResponse.prototype['id'] = undefined;

/**
 * @member {String} name
 */
EntityChildrenResponse.prototype['name'] = undefined;

/**
 * @member {module:model/EntityType} entityType
 */
EntityChildrenResponse.prototype['entityType'] = undefined;

/**
 * @member {String} timezone
 */
EntityChildrenResponse.prototype['timezone'] = undefined;

/**
 * @member {Array.<module:model/EntityChild>} children
 */
EntityChildrenResponse.prototype['children'] = undefined;






export default EntityChildrenResponse;

