/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityDataLocation from './EntityDataLocation';
import EntityType from './EntityType';
import TagData from './TagData';

/**
 * The EntityData model module.
 * @module model/EntityData
 * @version 6.0.1
 */
class EntityData {
    /**
     * Constructs a new <code>EntityData</code>.
     * @alias module:model/EntityData
     * @param id {String} 
     * @param name {String} 
     * @param entityType {module:model/EntityType} 
     * @param timezone {String} 
     */
    constructor(id, name, entityType, timezone) { 
        
        EntityData.initialize(this, id, name, entityType, timezone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, entityType, timezone) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['entityType'] = entityType;
        obj['timezone'] = timezone;
    }

    /**
     * Constructs a <code>EntityData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityData} obj Optional instance to populate.
     * @return {module:model/EntityData} The populated <code>EntityData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityData();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('entityType')) {
                obj['entityType'] = EntityType.constructFromObject(data['entityType']);
            }
            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('destinationId')) {
                obj['destinationId'] = ApiClient.convertToType(data['destinationId'], 'String');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = EntityDataLocation.constructFromObject(data['location']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [TagData]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
EntityData.prototype['id'] = undefined;

/**
 * @member {String} name
 */
EntityData.prototype['name'] = undefined;

/**
 * @member {module:model/EntityType} entityType
 */
EntityData.prototype['entityType'] = undefined;

/**
 * @member {String} parentId
 */
EntityData.prototype['parentId'] = undefined;

/**
 * @member {String} destinationId
 */
EntityData.prototype['destinationId'] = undefined;

/**
 * @member {String} timezone
 */
EntityData.prototype['timezone'] = undefined;

/**
 * @member {module:model/EntityDataLocation} location
 */
EntityData.prototype['location'] = undefined;

/**
 * @member {Array.<module:model/TagData>} tags
 */
EntityData.prototype['tags'] = undefined;






export default EntityData;

