/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LiveStatusType.
* @enum {}
* @readonly
*/
export default class LiveStatusType {
    
        /**
         * value: "OPERATING"
         * @const
         */
        "OPERATING" = "OPERATING";

    
        /**
         * value: "DOWN"
         * @const
         */
        "DOWN" = "DOWN";

    
        /**
         * value: "CLOSED"
         * @const
         */
        "CLOSED" = "CLOSED";

    
        /**
         * value: "REFURBISHMENT"
         * @const
         */
        "REFURBISHMENT" = "REFURBISHMENT";

    

    /**
    * Returns a <code>LiveStatusType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LiveStatusType} The enum <code>LiveStatusType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

