/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LiveQueueSTANDBY model module.
 * @module model/LiveQueueSTANDBY
 * @version 6.0.0
 */
class LiveQueueSTANDBY {
    /**
     * Constructs a new <code>LiveQueueSTANDBY</code>.
     * @alias module:model/LiveQueueSTANDBY
     */
    constructor() { 
        
        LiveQueueSTANDBY.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LiveQueueSTANDBY</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LiveQueueSTANDBY} obj Optional instance to populate.
     * @return {module:model/LiveQueueSTANDBY} The populated <code>LiveQueueSTANDBY</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LiveQueueSTANDBY();

            if (data.hasOwnProperty('waitTime')) {
                obj['waitTime'] = ApiClient.convertToType(data['waitTime'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} waitTime
 */
LiveQueueSTANDBY.prototype['waitTime'] = undefined;






export default LiveQueueSTANDBY;

