/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BoardingGroupState from './BoardingGroupState';

/**
 * The LiveQueueBOARDINGGROUP model module.
 * @module model/LiveQueueBOARDINGGROUP
 * @version 6.0.1
 */
class LiveQueueBOARDINGGROUP {
    /**
     * Constructs a new <code>LiveQueueBOARDINGGROUP</code>.
     * @alias module:model/LiveQueueBOARDINGGROUP
     */
    constructor() { 
        
        LiveQueueBOARDINGGROUP.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LiveQueueBOARDINGGROUP</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LiveQueueBOARDINGGROUP} obj Optional instance to populate.
     * @return {module:model/LiveQueueBOARDINGGROUP} The populated <code>LiveQueueBOARDINGGROUP</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LiveQueueBOARDINGGROUP();

            if (data.hasOwnProperty('allocationStatus')) {
                obj['allocationStatus'] = BoardingGroupState.constructFromObject(data['allocationStatus']);
            }
            if (data.hasOwnProperty('currentGroupStart')) {
                obj['currentGroupStart'] = ApiClient.convertToType(data['currentGroupStart'], 'Date');
            }
            if (data.hasOwnProperty('currentGroupEnd')) {
                obj['currentGroupEnd'] = ApiClient.convertToType(data['currentGroupEnd'], 'Date');
            }
            if (data.hasOwnProperty('nextAllocationTime')) {
                obj['nextAllocationTime'] = ApiClient.convertToType(data['nextAllocationTime'], 'Date');
            }
            if (data.hasOwnProperty('estimatedWait')) {
                obj['estimatedWait'] = ApiClient.convertToType(data['estimatedWait'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BoardingGroupState} allocationStatus
 */
LiveQueueBOARDINGGROUP.prototype['allocationStatus'] = undefined;

/**
 * @member {Date} currentGroupStart
 */
LiveQueueBOARDINGGROUP.prototype['currentGroupStart'] = undefined;

/**
 * @member {Date} currentGroupEnd
 */
LiveQueueBOARDINGGROUP.prototype['currentGroupEnd'] = undefined;

/**
 * @member {Date} nextAllocationTime
 */
LiveQueueBOARDINGGROUP.prototype['nextAllocationTime'] = undefined;

/**
 * @member {Number} estimatedWait
 */
LiveQueueBOARDINGGROUP.prototype['estimatedWait'] = undefined;






export default LiveQueueBOARDINGGROUP;

