/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PriceData from './PriceData';
import ReturnTimeState from './ReturnTimeState';

/**
 * The LiveQueuePAIDRETURNTIME model module.
 * @module model/LiveQueuePAIDRETURNTIME
 * @version 6.0.0
 */
class LiveQueuePAIDRETURNTIME {
    /**
     * Constructs a new <code>LiveQueuePAIDRETURNTIME</code>.
     * @alias module:model/LiveQueuePAIDRETURNTIME
     */
    constructor() { 
        
        LiveQueuePAIDRETURNTIME.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LiveQueuePAIDRETURNTIME</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LiveQueuePAIDRETURNTIME} obj Optional instance to populate.
     * @return {module:model/LiveQueuePAIDRETURNTIME} The populated <code>LiveQueuePAIDRETURNTIME</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LiveQueuePAIDRETURNTIME();

            if (data.hasOwnProperty('state')) {
                obj['state'] = ReturnTimeState.constructFromObject(data['state']);
            }
            if (data.hasOwnProperty('returnStart')) {
                obj['returnStart'] = ApiClient.convertToType(data['returnStart'], 'Date');
            }
            if (data.hasOwnProperty('returnEnd')) {
                obj['returnEnd'] = ApiClient.convertToType(data['returnEnd'], 'Date');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = PriceData.constructFromObject(data['price']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ReturnTimeState} state
 */
LiveQueuePAIDRETURNTIME.prototype['state'] = undefined;

/**
 * @member {Date} returnStart
 */
LiveQueuePAIDRETURNTIME.prototype['returnStart'] = undefined;

/**
 * @member {Date} returnEnd
 */
LiveQueuePAIDRETURNTIME.prototype['returnEnd'] = undefined;

/**
 * @member {module:model/PriceData} price
 */
LiveQueuePAIDRETURNTIME.prototype['price'] = undefined;






export default LiveQueuePAIDRETURNTIME;

