/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScheduleEntry model module.
 * @module model/ScheduleEntry
 * @version 6.0.0
 */
class ScheduleEntry {
    /**
     * Constructs a new <code>ScheduleEntry</code>.
     * @alias module:model/ScheduleEntry
     * @param date {String} 
     * @param openingTime {Date} 
     * @param closingTime {Date} 
     * @param type {module:model/ScheduleEntry.TypeEnum} 
     */
    constructor(date, openingTime, closingTime, type) { 
        
        ScheduleEntry.initialize(this, date, openingTime, closingTime, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, openingTime, closingTime, type) { 
        obj['date'] = date;
        obj['openingTime'] = openingTime;
        obj['closingTime'] = closingTime;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>ScheduleEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScheduleEntry} obj Optional instance to populate.
     * @return {module:model/ScheduleEntry} The populated <code>ScheduleEntry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScheduleEntry();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('openingTime')) {
                obj['openingTime'] = ApiClient.convertToType(data['openingTime'], 'Date');
            }
            if (data.hasOwnProperty('closingTime')) {
                obj['closingTime'] = ApiClient.convertToType(data['closingTime'], 'Date');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} date
 */
ScheduleEntry.prototype['date'] = undefined;

/**
 * @member {Date} openingTime
 */
ScheduleEntry.prototype['openingTime'] = undefined;

/**
 * @member {Date} closingTime
 */
ScheduleEntry.prototype['closingTime'] = undefined;

/**
 * @member {module:model/ScheduleEntry.TypeEnum} type
 */
ScheduleEntry.prototype['type'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
ScheduleEntry['TypeEnum'] = {

    /**
     * value: "OPERATING"
     * @const
     */
    "OPERATING": "OPERATING",

    /**
     * value: "TICKETED_EVENT"
     * @const
     */
    "TICKETED_EVENT": "TICKETED_EVENT",

    /**
     * value: "PRIVATE_EVENT"
     * @const
     */
    "PRIVATE_EVENT": "PRIVATE_EVENT",

    /**
     * value: "EXTRA_HOURS"
     * @const
     */
    "EXTRA_HOURS": "EXTRA_HOURS",

    /**
     * value: "INFO"
     * @const
     */
    "INFO": "INFO"
};



export default ScheduleEntry;

