/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TagData model module.
 * @module model/TagData
 * @version 6.0.1
 */
class TagData {
    /**
     * Constructs a new <code>TagData</code>.
     * @alias module:model/TagData
     * @param tag {String} 
     * @param tagName {String} 
     */
    constructor(tag, tagName) { 
        
        TagData.initialize(this, tag, tagName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tag, tagName) { 
        obj['tag'] = tag;
        obj['tagName'] = tagName;
    }

    /**
     * Constructs a <code>TagData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TagData} obj Optional instance to populate.
     * @return {module:model/TagData} The populated <code>TagData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TagData();

            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
            if (data.hasOwnProperty('tagName')) {
                obj['tagName'] = ApiClient.convertToType(data['tagName'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], OneOfstringnumberobject);
            }
        }
        return obj;
    }


}

/**
 * @member {String} tag
 */
TagData.prototype['tag'] = undefined;

/**
 * @member {String} tagName
 */
TagData.prototype['tagName'] = undefined;

/**
 * @member {String} id
 */
TagData.prototype['id'] = undefined;

/**
 * @member {module:model/OneOfstringnumberobject} value
 */
TagData.prototype['value'] = undefined;






export default TagData;

