/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DestinationsResponse from '../model/DestinationsResponse';

/**
* Destinations service.
* @module api/DestinationsApi
* @version 6.0.0
*/
export default class DestinationsApi {

    /**
    * Constructs a new DestinationsApi. 
    * @alias module:api/DestinationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get a list of supported destinations available on the live API
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DestinationsResponse} and HTTP response
     */
    getDestinationsWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DestinationsResponse;
      return this.apiClient.callApi(
        '/destinations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a list of supported destinations available on the live API
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DestinationsResponse}
     */
    getDestinations() {
      return this.getDestinationsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
