import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';

const SPEC_URL = 'https://api.themeparks.wiki/docs/v1.yaml';
const OUTPUT = resolve(process.cwd(), 'src/_generated/schema.ts');

const header = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/regenerate.ts from ${SPEC_URL}.
 * Do not edit by hand. Run \`npm run regenerate\` to update.
 */
`;

async function main() {
  const ast = await openapiTS(new URL(SPEC_URL));
  const body = astToString(ast);
  await writeFile(OUTPUT, header + body, 'utf8');
  console.log(`Wrote ${OUTPUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
