/**
 * Theme Parks Wiki V1 API
 * api.themeparks.wiki
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Themeparks);
  }
}(this, function(expect, Themeparks) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Themeparks.LiveQueue();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LiveQueue', function() {
    it('should create an instance of LiveQueue', function() {
      // uncomment below and update the code to test LiveQueue
      //var instance = new Themeparks.LiveQueue();
      //expect(instance).to.be.a(Themeparks.LiveQueue);
    });

    it('should have the property STANDBY (base name: "STANDBY")', function() {
      // uncomment below and update the code to test the property STANDBY
      //var instance = new Themeparks.LiveQueue();
      //expect(instance).to.be();
    });

    it('should have the property SINGLE_RIDER (base name: "SINGLE_RIDER")', function() {
      // uncomment below and update the code to test the property SINGLE_RIDER
      //var instance = new Themeparks.LiveQueue();
      //expect(instance).to.be();
    });

    it('should have the property RETURN_TIME (base name: "RETURN_TIME")', function() {
      // uncomment below and update the code to test the property RETURN_TIME
      //var instance = new Themeparks.LiveQueue();
      //expect(instance).to.be();
    });

    it('should have the property PAID_RETURN_TIME (base name: "PAID_RETURN_TIME")', function() {
      // uncomment below and update the code to test the property PAID_RETURN_TIME
      //var instance = new Themeparks.LiveQueue();
      //expect(instance).to.be();
    });

    it('should have the property BOARDING_GROUP (base name: "BOARDING_GROUP")', function() {
      // uncomment below and update the code to test the property BOARDING_GROUP
      //var instance = new Themeparks.LiveQueue();
      //expect(instance).to.be();
    });

  });

}));
